project:
  type: website
  output-dir: docs

resources:
  - _images

website:
  title: "values_from_lyrics_ISMIR2025"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



